config/routes.rb
Rails.application.routes.draw do

  root 'starships#index'
  resources :starships, only: [:index]

end

app/models/starship.rb
class Starship 
  def initialize(name)
    get_starship(name)
  end

  def self.starship_names
    starships = get_starships
    starships.map{ |starship| starship['name']}
  end

  def self.starship_facts
    ['name', 'manufacturer', 'hyperdrive_rating', 'starship_class']
  end

  def get(fact)
    @starship[fact]
  end

  private

  def self.get_starships
    results = RestClient.get('http://swapi.co/api/starships/')
    data = JSON.load(results)
    data['results']
  end

  def get_starship(name)
    starships = self.class.get_starships
    @starship = starships.find{ |starship| starship['name'] == name }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/starships_controller.rb
class StarshipsController < ApplicationController
  def index
    @starship_names = Starship.starship_names
    @starship_facts = Starship.starship_facts

    if params[:starship_name]
      @starship = Starship.new(params[:starship_name])
      @fact = params[:starship_fact]
      @value = @starship.get(@fact)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/starships_helper.rb
module StarshipsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BEWDFinalproject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/starships/index.html.erb
<h1> Starship Textbook </h1>

<h2> Choose options from the dropdown menu to learn more about the Starship fleet in a galaxy far far away </h2>

<%= form_tag starships_path, method: 'get' do  %>
  What is the
  <div>
    <label> Ship Attributes </label>
    <%= select_tag(:starship_fact, options_for_select(@starship_facts.map{|starship| [starship, starship]}))%>
  </div>

  of the
  <div>
    <label> Ship names </label>
    <%= select_tag(:starship_name, options_for_select(@starship_names.map{|starship| [starship, starship]}))%>
  </div>
  ?

 <%= submit_tag 'Submit' %>
 <%end %>

 <div>
   <%= @value %> is the <%= @fact %> of  <%= @starship.get("name") %>